request to merge assignment 3 into develop branch
munendra-successive/backend-training pull request #3
Opened 2023-11-20 12:42 UTC by munendra-successive

4. Develop a data seeding module that generates mock API responses.

5. Create a sample POST API that returns a seeded data as a response.

6. Develop an authentication middleware using a JWT dummy token.
7. 
8. Integrate the authentication middleware with the previously created APIs.

2023-12-07 18:47 UTC, UrvashiChaudhary requested changes

2023-12-07 18:47 UTC, UrvashiChaudhary commented on src/MiddleWares/index.js
> +import Logger from "./Logger.js";
Please fix the naming convention of the **Logger** import

2023-12-07 18:47 UTC, UrvashiChaudhary commented on src/MiddleWares/rateLimit.js
> +function loadUserRequests() {
please use arrow functions

2023-12-07 18:47 UTC, UrvashiChaudhary commented on src/controllers/UserController.js
We write controller functions name in camel case

2023-12-07 18:47 UTC, UrvashiChaudhary commented on src/controllers/UserController.js
> +
Make the seeding module in utils folder and use it from there in the controllers to return the APIs responses

2023-12-07 18:47 UTC, UrvashiChaudhary commented on src/routes/otherRoutes.js
Remove them if they are of no use

2023-12-08 05:03 UTC, munendra-successive commented on src/routes/otherRoutes.js
Removed

2023-12-08 05:04 UTC, munendra-successive commented on src/controllers/UserController.js
> +
Done

2023-12-08 05:06 UTC, munendra-successive commented on src/MiddleWares/rateLimit.js
> +function loadUserRequests() {
done

2023-12-08 05:07 UTC, munendra-successive commented on src/MiddleWares/index.js
> +import Logger from "./Logger.js";
done

2023-12-12 13:04 UTC, suraj-bha approved these changes

2023-12-12 13:06 UTC, merged